# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/muram/fpga-signal-processing/vivado/fpga_signal_processing/fpga_signal_processing.srcs/sources_1/ip/FftCore/FftCore.xci
# IP: The module: 'FftCore' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/muram/fpga-signal-processing/vivado/fpga_signal_processing/fpga_signal_processing.gen/sources_1/ip/FftCore/FftCore_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FftCore'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/muram/fpga-signal-processing/vivado/fpga_signal_processing/fpga_signal_processing.srcs/sources_1/ip/FftCore/FftCore.xci
# IP: The module: 'FftCore' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/muram/fpga-signal-processing/vivado/fpga_signal_processing/fpga_signal_processing.gen/sources_1/ip/FftCore/FftCore_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FftCore'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
